name: zennapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.3
  firebase_core: ^1.17.1
  firebase_database: ^9.0.15
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ico_lamb.jpeg"
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/ico_lamb.jpeg'